---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: centos-7
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          path: molecule_demo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo
          sudo yum -y install podman
          python3 -m pip install --upgrade pip
          python3 -m pip install "molecule[podman,lint]"
      - name: Test with molecule
        run: |
          molecule init role first-mol
          cd first-mol
          molecule test
